name: Litton7
channels:
  - pytorch
dependencies:
  - pytorch>=2.0.*
  - torchvision
  - cpuonly
  - conda-forge::numpy==1.26.*
  - conda-forge::pandas==2.2.*
  - conda-forge::pillow
  - conda-forge::gdown
